
192.78.98.48

[frontend]
192.78.98.45
192.78.98.46 name1="global var from inventory"
192.78.98.47 desc="this is from frontend"


[backend]
192.78.98.45
192.78.98.46
192.78.98.47

[web]
172.31.73.202

[local]
localhost ansible_connection=local

[local:vars]
name="Madhu - from inventory!!"

[frontend:vars]
desc1="this is from frontend vars"
